trigger:
- main

pool:
  name: Default

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'maven-examples/maven-example/pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- script: echo "✅ Build completed on Mukhila's self-hosted agent"
